import { useState, useRef, useEffect } from 'react';
import {
  Download,
  RefreshCw,
  AlertTriangle,
  ShieldCheck,
  FileJson,
  FileSpreadsheet,
  FileText,
  ChevronDown,
} from 'lucide-react';
import EcosystemBadge from '../EcosystemBadge.jsx';

export default function PackageHeader({
  pkg,
  isVulnerable,
  shortestPathsCount,
  upstreamCount,
  directDepCount,
  onRescan,
}) {
  const [showExportMenu, setShowExportMenu] = useState(false);
  const menuRef = useRef(null);

  // Close dropdown on outside click
  useEffect(() => {
    function handleClickOutside(e) {
      if (menuRef.current && !menuRef.current.contains(e.target)) {
        setShowExportMenu(false);
      }
    }
    if (showExportMenu) {
      document.addEventListener('mousedown', handleClickOutside);
    }
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [showExportMenu]);

  function downloadFile(content, fileName, mimeType) {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    a.click();
    URL.revokeObjectURL(url);
    setShowExportMenu(false);
  }

  function exportJSON() {
    const manifest = JSON.stringify(pkg, null, 2);
    downloadFile(manifest, `${pkg.name}-dossier.json`, 'application/json');
  }

  function exportCSV() {
    const headers = ['Package Name', 'Ecosystem', 'Version', 'License', 'Maintainer', 'Security Status', 'Reachable CVEs'];
    const row = [
      `"${pkg.name}"`,
      `"${pkg.ecosystem || 'npm'}"`,
      `"${pkg.latestVersion || '1.0.0'}"`,
      `"${pkg.licenses?.[0]?.spdxId || 'MIT'}"`,
      `"${pkg.maintainers?.[0]?.name || 'Unknown'}"`,
      `"${isVulnerable ? 'VULNERABLE' : 'VERIFIED CLEAN'}"`,
      `"${shortestPathsCount}"`,
    ];
    const csvContent = `${headers.join(',')}\n${row.join(',')}\n`;
    downloadFile(csvContent, `${pkg.name}-audit.csv`, 'text/csv;charset=utf-8;');
  }

  function exportMarkdown() {
    const md = [
      `# Security Audit Dossier: ${pkg.name}`,
      `**Ecosystem**: ${pkg.ecosystem} | **Version**: ${pkg.latestVersion || '1.0.0'} | **License**: ${pkg.licenses?.[0]?.spdxId || 'MIT'}`,
      `**Maintainer**: ${pkg.maintainers?.[0]?.name || pkg.maintainers?.[0]?.email || 'Ecosystem Core'}`,
      '',
      `## Executive Status`,
      `- **Security State**: ${isVulnerable ? '⚠️ VULNERABLE' : '✅ VERIFIED CLEAN'}`,
      `- **Reachable Attack Paths**: ${shortestPathsCount}`,
      `- **Upstream Blast Radius**: ${upstreamCount} packages`,
      `- **Direct Dependencies**: ${directDepCount} dependencies`,
      '',
      `*Generated by CognoDB Supply Chain Dependency Explorer on ${new Date().toISOString()}*`,
    ].join('\n');
    downloadFile(md, `${pkg.name}-report.md`, 'text/markdown;charset=utf-8;');
  }

  return (
    <>
      <header
        style={{
          borderBottom: '1px solid var(--color-primary)',
          paddingBottom: '2rem',
          marginBottom: '2rem',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'flex-start',
          flexWrap: 'wrap',
          gap: '1.5rem',
        }}
      >
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.75rem' }}>
            <EcosystemBadge ecosystem={pkg.ecosystem} />
            <span style={{ fontSize: '0.7rem', border: '1px solid var(--color-outline)', padding: '0.15rem 0.45rem', textTransform: 'uppercase', color: 'var(--color-outline)' }}>
              PUBLIC REGISTRY
            </span>
            {isVulnerable ? (
              <span className="severity-pill critical">● VULNERABLE</span>
            ) : (
              <span className="severity-pill safe">● VERIFIED CLEAN</span>
            )}
          </div>

          <h1 style={{ fontFamily: 'var(--font-serif)', fontSize: '2.5rem', fontWeight: 600, color: 'var(--color-primary)', letterSpacing: '-0.02em', lineHeight: 1.1 }}>
            {pkg.name}
          </h1>

          <div style={{ display: 'flex', alignItems: 'center', gap: '1.25rem', marginTop: '0.75rem', fontSize: '0.85rem', color: 'var(--color-on-surface-variant)', flexWrap: 'wrap' }}>
            <span>
              Version: <strong style={{ color: 'var(--color-primary)' }}>{pkg.latestVersion || '1.0.0'}</strong>
            </span>
            <span style={{ color: 'var(--color-outline-variant)' }}>|</span>
            <span>
              License:{' '}
              <strong style={{ color: 'var(--color-primary)' }}>
                {pkg.licenses?.[0]?.spdxId || 'MIT'}
              </strong>
            </span>
            <span style={{ color: 'var(--color-outline-variant)' }}>|</span>
            <span>
              Maintainer:{' '}
              <strong style={{ color: 'var(--color-primary)' }}>
                {pkg.maintainers?.[0]?.name || pkg.maintainers?.[0]?.email || 'Ecosystem Core'}
              </strong>
            </span>
          </div>
        </div>

        <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center', position: 'relative' }} ref={menuRef}>
          {/* Multi-Format Export Dropdown */}
          <div style={{ position: 'relative' }}>
            <button
              type="button"
              className="btn-ink"
              onClick={() => setShowExportMenu((prev) => !prev)}
              aria-haspopup="true"
              aria-expanded={showExportMenu}
              style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}
            >
              <Download size={15} />
              <span>Export Dossier</span>
              <ChevronDown size={13} />
            </button>

            {showExportMenu && (
              <div
                style={{
                  position: 'absolute',
                  top: '100%',
                  right: 0,
                  marginTop: '0.35rem',
                  background: '#ffffff',
                  border: '1px solid var(--color-primary)',
                  boxShadow: '3px 3px 0px var(--color-primary)',
                  zIndex: 50,
                  minWidth: '200px',
                  display: 'flex',
                  flexDirection: 'column',
                }}
              >
                <button
                  type="button"
                  onClick={exportJSON}
                  style={{
                    background: 'none',
                    border: 'none',
                    borderBottom: '1px solid var(--color-outline-variant)',
                    padding: '0.65rem 1rem',
                    textAlign: 'left',
                    fontFamily: 'var(--font-mono)',
                    fontSize: '0.75rem',
                    color: 'var(--color-primary)',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '0.6rem',
                    cursor: 'pointer',
                  }}
                  onMouseEnter={(e) => (e.currentTarget.style.background = 'var(--color-surface-container)')}
                  onMouseLeave={(e) => (e.currentTarget.style.background = 'transparent')}
                >
                  <FileJson size={16} />
                  <span>JSON Manifest (.json)</span>
                </button>

                <button
                  type="button"
                  onClick={exportCSV}
                  style={{
                    background: 'none',
                    border: 'none',
                    borderBottom: '1px solid var(--color-outline-variant)',
                    padding: '0.65rem 1rem',
                    textAlign: 'left',
                    fontFamily: 'var(--font-mono)',
                    fontSize: '0.75rem',
                    color: 'var(--color-primary)',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '0.6rem',
                    cursor: 'pointer',
                  }}
                  onMouseEnter={(e) => (e.currentTarget.style.background = 'var(--color-surface-container)')}
                  onMouseLeave={(e) => (e.currentTarget.style.background = 'transparent')}
                >
                  <FileSpreadsheet size={16} />
                  <span>CSV Spreadsheet (.csv)</span>
                </button>

                <button
                  type="button"
                  onClick={exportMarkdown}
                  style={{
                    background: 'none',
                    border: 'none',
                    padding: '0.65rem 1rem',
                    textAlign: 'left',
                    fontFamily: 'var(--font-mono)',
                    fontSize: '0.75rem',
                    color: 'var(--color-primary)',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '0.6rem',
                    cursor: 'pointer',
                  }}
                  onMouseEnter={(e) => (e.currentTarget.style.background = 'var(--color-surface-container)')}
                  onMouseLeave={(e) => (e.currentTarget.style.background = 'transparent')}
                >
                  <FileText size={16} />
                  <span>Markdown Report (.md)</span>
                </button>
              </div>
            )}
          </div>

          <button
            type="button"
            className="btn-ink btn-ink-primary"
            onClick={onRescan}
            style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}
          >
            <RefreshCw size={14} />
            Rescan
          </button>
        </div>
      </header>

      {/* Security Status Banner */}
      <div
        className="ink-card"
        style={{
          borderColor: isVulnerable ? 'var(--color-error)' : 'var(--color-safe)',
          background: isVulnerable ? 'var(--color-error-bg)' : 'var(--color-safe-bg)',
          marginBottom: '2rem',
          padding: '1.25rem 1.5rem',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '1rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
            {isVulnerable ? (
              <AlertTriangle size={26} color="var(--color-error)" />
            ) : (
              <ShieldCheck size={26} color="var(--color-safe)" />
            )}
            <div>
              <h4 style={{ fontFamily: 'var(--font-serif)', fontSize: '1.1rem', fontWeight: 700, color: isVulnerable ? 'var(--color-error)' : 'var(--color-safe)' }}>
                {isVulnerable
                  ? `Security Advisory Alert: ${shortestPathsCount} Reachable Attack Path${shortestPathsCount === 1 ? '' : 's'}`
                  : 'Ledger Audit Status: Verified Clean'}
              </h4>
              <p style={{ fontSize: '0.8rem', color: isVulnerable ? '#752121' : '#137333', marginTop: '0.2rem' }}>
                {isVulnerable
                  ? `Transitive dependency analysis detected vulnerability exposure within 1–4 hops of ${pkg.name}.`
                  : `No known CVE records mapped in direct or transitive dependency chains.`}
              </p>
            </div>
          </div>

          <div style={{ display: 'flex', gap: '1.5rem', fontSize: '0.8rem', fontFamily: 'var(--font-mono)' }}>
            <div>
              <span style={{ color: 'var(--color-outline)', display: 'block', fontSize: '0.7rem' }}>UPSTREAM BLAST RADIUS</span>
              <strong>{upstreamCount} packages</strong>
            </div>
            <div>
              <span style={{ color: 'var(--color-outline)', display: 'block', fontSize: '0.7rem' }}>DIRECT DEPENDENCIES</span>
              <strong>{directDepCount} deps</strong>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
